/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:00e9998f-9fc3-4f96-b830-e28c3fa8aad6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_GJhCSX3Pd",
    "aws_user_pools_web_client_id": "1s7cjs1jn6dcci7u5aovr2ibho",
    "oauth": {},
    "aws_user_files_s3_bucket": "promptbucket134850-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
